package com.gondroid.rayacashapp.data.database

import androidx.room.ConstructedBy
import androidx.room.Database
import androidx.room.RoomDatabase
import androidx.room.RoomDatabaseConstructor
import com.gondroid.rayacashapp.data.database.dao.BalanceDAO
import com.gondroid.rayacashapp.data.database.entity.BalanceEntity
import com.gondroid.rayacashapp.data.database.entity.TransactionEntity

const val DATABASE_NAME = "raya_app_database.db"

// ignore alert, this is generated by room
expect object RayaCashCTor : RoomDatabaseConstructor<RayaCashDatabase>

expect fun generateUUID(): String

@Database(entities = [BalanceEntity::class, TransactionEntity::class], version = 1)
@ConstructedBy(RayaCashCTor::class)
abstract class RayaCashDatabase : RoomDatabase() {
    abstract fun getBalanceDao(): BalanceDAO
}